### ISSUE TITLE
Minified React error 425

### ISSUE THREAD

**Issue by amay077** [amay077/gatsby-starter-netlify-cms#7]
Top ページでなんかエラー出てる。 prod で。

![image](https://user-images.githubusercontent.com/401369/224520611-38182e4e-7e2d-4cbe-b9da-f7ac84221930.png)

```
Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:118:466)
    at Ku (react-dom.production.min.js:227:369)
    at ws (react-dom.production.min.js:281:85)
    at ks (react-dom.production.min.js:280:450)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:268:209)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
Zr @ react-dom.production.min.js:118
Ku @ react-dom.production.min.js:227
ws @ react-dom.production.min.js:281
ks @ react-dom.production.min.js:280
ys @ react-dom.production.min.js:280
vs @ react-dom.production.min.js:280
as @ react-dom.production.min.js:268
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14

```

**Comment by amay077** [comment]
fixed
